### ISSUE TITLE
advanced-cache requests don't appear to send final segment

### ISSUE THREAD

**Issue by joehoyle** [humanmade/aws-xray#59]
It looks like when a page is served via advanced-cache.php (such as batcache) the end trace statement doesn't come through.

**Comment by rmccue** [comment]
This seems to be due to X-Ray using [the shutdown action instead of a handler](https://github.com/humanmade/aws-xray/blob/master/inc/namespace.php#L27-L31). However, the shutdown handler that fires the action is only registered [after advanced-cache.php is loaded](https://github.com/WordPress/wordpress-develop/blob/48df8c3646e597738b74c73d56183005c00b4b4a/src/wp-settings.php#L148)

**Comment by joehoyle** [comment]
this is no longer an issue
